spring:
  security:
    user:
      name: admin
      password: secret123
  application:
  name: project
  datasource:
    url: jdbc:postgresql://localhost:5432/MiniProject
    username: postgres
    password: megha

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
        hibernate:
          format_sql: true